"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useLocale, useTranslations } from "next-intl";
import type { Locale } from "@/i18n/routing";

type PagefindResultData = {
  url: string;
  meta: { title?: string };
  excerpt: string;
};

type PagefindApi = {
  search: (
    term: string,
  ) => Promise<{ results: { id: string; data: () => Promise<PagefindResultData> }[] }>;
};

declare global {
  interface Window {
    __pagefind?: Promise<PagefindApi>;
  }
}

function loadPagefind(): Promise<PagefindApi> {
  // Generated by the postbuild pagefind script (see package.json) straight
  // into public/, so it only exists after a real build — webpackIgnore keeps
  // Next's bundler from trying to resolve this at build time. The path is
  // built from a variable (rather than a string literal) so TypeScript
  // doesn't attempt to statically resolve it either.
  const pagefindPath = "/pagefind/pagefind.js";
  window.__pagefind ??= import(/* webpackIgnore: true */ pagefindPath) as Promise<PagefindApi>;
  return window.__pagefind;
}

export function SearchClient() {
  const locale = useLocale() as Locale;
  const t = useTranslations("search");
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<PagefindResultData[]>([]);
  const [loading, setLoading] = useState(false);
  const requestId = useRef(0);

  useEffect(() => {
    const term = query.trim();
    if (!term) {
      setResults([]);
      setLoading(false);
      return;
    }

    const id = ++requestId.current;
    setLoading(true);
    const timeout = setTimeout(async () => {
      const pagefind = await loadPagefind();
      const search = await pagefind.search(term);
      const data = await Promise.all(search.results.map((r) => r.data()));
      if (id !== requestId.current) return; // a newer query started, discard this response
      // Pagefind's url is the crawled build file's path (e.g. "/en.html",
      // "/en/changelog.html") since it was pointed at .next/server/app rather
      // than a real static export — strip the extension to get the actual
      // served route.
      const normalized = data.map((d) => ({ ...d, url: d.url.replace(/\.html$/, "") }));
      setResults(
        normalized.filter((d) => d.url === `/${locale}` || d.url.startsWith(`/${locale}/`)),
      );
      setLoading(false);
    }, 150);

    return () => clearTimeout(timeout);
  }, [query, locale]);

  return (
    <div>
      <input
        type="search"
        value={query}
        onChange={(e) => setQuery(e.target.value)}
        placeholder={t("placeholder")}
        autoFocus
        className="panel-card w-full px-4 py-3 font-mono text-paper placeholder:text-paper/40 focus:border-teal focus:outline-none"
      />

      <div className="mt-8 flex flex-col gap-4">
        {loading && <p className="label-mono text-paper/50">{t("searching")}</p>}
        {!loading && query.trim() !== "" && results.length === 0 && (
          <p className="text-paper/50">{t("noResults", { query: query.trim() })}</p>
        )}
        {results.map((result) => (
          <Link
            key={result.url}
            href={result.url}
            className="panel-card group block p-4 transition hover:border-teal"
          >
            <h2
              className="font-display text-lg font-medium transition group-hover:text-amber"
              dangerouslySetInnerHTML={{ __html: result.meta.title ?? result.url }}
            />
            <p
              className="mt-2 text-sm text-paper/70 [&_mark]:bg-transparent [&_mark]:text-teal"
              dangerouslySetInnerHTML={{ __html: result.excerpt }}
            />
          </Link>
        ))}
      </div>
    </div>
  );
}
